server:
  port: 8080

spring:
  application:
    name: api-gateway-service

# Additional gateway-specific configurations
gateway:
  routes:
    # Configure routes for each service here
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
