spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${server.port}