spring:
  application:
    name: api-gateway-service  # Replace with the service’s name
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
